travis:
  secure:
    BINSTAR_TOKEN: prbgCOb+LfAT4ggCN0bpwK5/d2z/LDCe9/p+xtoh/y58qShgb8tV7E9GjOmr7XRCdIiUCDNXalTI/rcSPIvpSWWNKl+nHfVfpl3bqjIzOf2JITgAbne09/mDNKndIobVOqZ4YL2l9w7Tgr0E3E4sbXzrWrYVSjasim2YNFooQM1qNprZ8ACP5ZuxJyxIheZ8el8puWpMJ2lluQWrQo2wuMVVh1Q1Xz4WPjXRAwZWGRFabAZVa0uga9G0lv4h75tIwYgRBT/7IXkTkxTIoBb0Ixp0wG5YaA/1YwKTu+/I+49Tmx0L/w9fKIAmzVsbTY4eB7LEhYZJIRQjodx6m+h5YA+v0aV13ScX0+E5ZtAKYXyFYCxJyyPwHofp+msTd9WPCRLRyDCVWQez/iQ7ewwrMv1k1OONLeWxGQFAe4kesOWXCMNpTonSXNx/sN8Ly7J10Ylz8t9E4fmx+ZwaWaUuXAiBb+q8NTlLSsmXfsC6dQc6+baZbaMBx0hbNSW3EgI0Tca6KTPUb5co6pG2CkmI8XxwKtQj7rDB+Q3SMYcB/ap/PJ6jLQWsxLC2WgcXN1qBfxEA995iEJ1vgn7IPlGXOGGlB9nwOrdPC5N6miiesB5JOJ9trvhXG0JBv1O05H6zmxHHgP3MVJPAgEjuMWJwA0D+eDe2EafBR7RCusE5y+4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
