travis:
  secure:
    BINSTAR_TOKEN: tE/TsgBrFJl0Az0AE+XVpVLYrMhWzseo+N8QRR1jmS9P3uS30gh37EXAAuHF3umvj3Pw6l6/SbUf3QhHWB1rKZZ1K/uir0vfywXhlOhjbZTdPJam+Z71ljrEWJ+GDExyZ18TRPRNcQBauQSoru/168WTrj5g6IDiURIMNfDHv3DIZdzl9xmb3Un9DPDj5UUeZt2NyIQjtQYmBbUfKz13+liQWsbbT3yYy0PrdLr7kkz42g16KuCs0Qw1Ma6XaBNFCY452grh45GWUNTN0zsdlTg00eBBp+jiR3ad9Z7nTCcj7w5U0ndweShfd/70Q3oDpnLHSUogpsG0FuEcXHRo3BbaDEMwJ/+wIOJafZ5t+AGvnkOAslusg9E23/VcpJgNsOMGSGrfnNHT329RWTj/BxOkNWZZk1HUZXRPFGN6JDdET/cjq3hVVpt6s2JREG7Bu9lXwigg/z1F7P4YxcteiRgEngTUjP6ArevTMSMt72N8ZEvDugqeFhaKT337j/If+iG1dHYBbKYbm1qAvTEPXrD4E2gUEA6Xms/OG4Nbirvhga2OjjMxvVlgUyV+sAAUjAiooePGrAWw4c2lT6ys+BkT2g5SRbgzI/uh+0QXKBbyAOwdGNTwvUIMWp1XJuH3HO6uSGb4qGOG9tdWgS3gor75dc3twpPEcxmc3skn/84=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
