travis:
  secure:
    BINSTAR_TOKEN: OU8lq0On9XB0dTAmPP8uIC8qPCsVkQUAGA1SxvG1MYjnfGCeF9RMvYCBApKIhWOCE3jR/TvopqxmjyTXVoxu5cIbwLyBdUkF/+ChnfTf3nRMcn5BPOvuqCeSLKl0NbrPCsi8Shb5uM9BZ9X7/T2jitH11DmSctjyP0zjfsDTw/9+JoLgvKBh84X4PYDRN1GMSFBiDzCCzdyWXrmblxkSYjYMI+5tJYqRPitUlE5j77gaBg/uAjDHvK9Puy1/fTzrawfAQDUHN2RqL8b+p1BzEadW/kB1cuHt4h7QH4XDjcHeLLmhJmatnWbRjubN42Ib0OUK5sYvmaDmmGqczyumhBf0Nc453rkI1mTIOXhHLjXi/jD05ty2aueNq93MJ9CrWjn1NDnEe4WQgD5rubxBrdFlSOfzu0kWT7UZq3vrl199VCHy5JQTgwLSrfDGzKr8+yJFBZg0fPw7sCCPTdnipXhJfEJrJtyANeMsH2Tf9X5CgQJQHbbs0yFb5LCMt16HPtDVi+fc0mMp+CedkoegmV0ftzivQLfNm0IPZ3yIvtmIyZITHNnPc8l0l7SxfrvH2jW1vxML7S1nIbWeMkpsa1wS20hCtpq33f1vojO2V+iVH1O3DCmKosK9kqUzSjSE3XtjLV48WCUOofYJFbNLHbVf6df4ydaQxNbd7HxNICo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
